name: Sync to HuggingFace hub - semmyKG
on:
  push:
    branches: [main]

  # assist: https://huggingface.co/docs/hub/en/spaces-github-actions
  ### git remote add space https://huggingface.co/spaces/HF_USERNAME/SPACE_NAME   #Add space repo
  ### git remote add space https://huggingface.co/spaces/semmyk/semmyKG
  ### git push --force space main   #force push to sync everything for the first time
  
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        #run: git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/HF_USERNAME/SPACE_NAME main
        run: git push https://semmyk:$HF_TOKEN@huggingface.co/spaces/semmyk/semmyKG main
